image: salemove/chrome

build:
  before_script:
    - sudo chmod +x ./gradlew
    - sudo apt-get update
    - sudo apt-get install openjdk-8-jdk -y

  script:
    - ./gradlew clean test --info
    - ./gradlew allureReport

  artifacts:
    when: always
    paths:
      - build/reports/allure-report
    expire_in: 1 week
  only:
    - main

.post:
  stage: Report
  only:
    - main
  script:
    - mkdir public
    - mv build/reports/allure-report/* public
  artifacts:
    when: always
    paths:
      - public
    expire_in: 1 week