# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Run UI Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean test --info
    - name: Allure report V2
      # You may pin to the exact commit or the version.
      # uses: QuintilianoNery/action-allure-report-V2@0695401fc18f6a083fab548315fc10f1cc4f56e6
      uses: QuintilianoNery/action-allure-report-V2@0.2.0
      with:
        # Allure test result data dir
        results-dir: allure-results
        # Allure report target dir
        report-dir: allure-report
