name: Run UI Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            - ./gradlew clean test --info
            - ./gradlew allureReport
